"""
shared/utils/metadata.py — Metadatos de activos y mapeo de sectores.

Este módulo provee la base de conocimiento para la diversificación inteligente
del Orquestador.
"""

# Mapa de sectores para el S&P 500 y activos populares
SYMBOL_SECTORS = {
    # --- TECHNOLOGY & SEMICONDUCTORS ---
    "AAPL":  "Technology",
    "MSFT":  "Technology",
    "GOOGL": "Technology",
    "META":  "Technology",
    "NVDA":  "Technology",
    "AMD":   "Technology",
    "INTC":  "Technology",
    "AVGO":  "Technology",
    "QCOM":  "Technology",
    "AMAT":  "Technology",
    "MU":    "Technology",
    "ASML":  "Technology",
    "TSM":   "Technology",
    "ORCL":  "Technology",
    "CRM":   "Technology",
    "ADBE":  "Technology",
    "CSCO":  "Technology",
    "IBM":   "Technology",
    "NOW":   "Technology",
    "SNOW":  "Technology",
    "PLTR":  "Technology",
    "SHOP":  "Technology",
    "PANW":  "Technology",
    "CRWD":  "Technology",
    "MDB":   "Technology",
    "DDOG":  "Technology",
    "NET":   "Technology",
    "TEAM":  "Technology",
    "ADSK":  "Technology",
    "Z":     "Technology",
    
    # --- FINANCE & FINTECH ---
    "JPM":   "Finance",
    "BAC":   "Finance",
    "WFC":   "Finance",
    "C":     "Finance",
    "GS":    "Finance",
    "MS":    "Finance",
    "AXP":   "Finance",
    "V":     "Finance",
    "MA":    "Finance",
    "PYPL":  "Finance",
    "SQ":    "Finance",
    "COIN":  "Finance",
    "HOOD":  "Finance",
    "SOFI":  "Finance",
    "AFRM":  "Finance",
    "BLK":   "Finance",
    "SCHW":  "Finance",
    "BX":    "Finance",
    "KKR":   "Finance",
    "BK":    "Finance",
    "USB":   "Finance",
    "TFC":   "Finance",
    "PNC":   "Finance",
    
    # --- CONSUMER & RETAIL ---
    "AMZN":  "Consumer",
    "WMT":   "Consumer",
    "COST":  "Consumer",
    "TGT":   "Consumer",
    "HD":    "Consumer",
    "LOW":   "Consumer",
    "NKE":   "Consumer",
    "SBUX":  "Consumer",
    "MCD":   "Consumer",
    "TSLA":  "Consumer", # Automotriz/Consumer Discretionary
    "TM":    "Consumer",
    "F":     "Consumer",
    "GM":    "Consumer",
    "KO":    "Consumer",
    "PEP":   "Consumer",
    "PG":    "Consumer",
    "CL":    "Consumer",
    "HSY":   "Consumer",
    "K":     "Consumer",
    "GIS":   "Consumer",
    "MDLZ":  "Consumer",
    "PM":    "Consumer",
    "MO":    "Consumer",
    "LULU":  "Consumer",
    "DIS":   "Consumer",
    "NFLX":  "Consumer", # Entertainment/Consumer
    
    # --- HEALTHCARE & PHARMA ---
    "LLY":   "Healthcare",
    "UNH":   "Healthcare",
    "JNJ":   "Healthcare",
    "PFE":   "Healthcare",
    "MRK":   "Healthcare",
    "ABBV":  "Healthcare",
    "TMO":   "Healthcare",
    "DHR":   "Healthcare",
    "ISRG":  "Healthcare",
    "VRTX":  "Healthcare",
    "REGN":  "Healthcare",
    "AMGN":  "Healthcare",
    "GILD":  "Healthcare",
    "BMY":   "Healthcare",
    "CVS":   "Healthcare",
    "CI":    "Healthcare",
    "HUM":   "Healthcare",
    "SYK":   "Healthcare",
    "BSX":   "Healthcare",
    
    # --- ENERGY & INDUSTRIALS ---
    "XOM":   "Energy",
    "CVX":   "Energy",
    "COP":   "Energy",
    "EOG":   "Energy",
    "SLB":   "Energy",
    "OXY":   "Energy",
    "MPC":   "Energy",
    "HAL":   "Energy",
    "VLO":   "Energy",
    "CAT":   "Industrial",
    "DE":    "Industrial",
    "GE":    "Industrial",
    "HON":   "Industrial",
    "MMM":   "Industrial",
    "UPS":   "Industrial",
    "FDX":   "Industrial",
    "LMT":   "Industrial",
    "RTX":   "Industrial",
    "NOC":   "Industrial",
    "BA":    "Industrial",
    "WM":    "Industrial",
}

def get_sector_for(symbol: str) -> str:
    """Devuelve el sector de un símbolo o 'Other' si no está mapeado."""
    return SYMBOL_SECTORS.get(symbol.upper(), "Other")
